# .streamlit/config.toml

[server]
# port = 8501  # opcional

[theme]
base = "dark"
primaryColor = "#ff7f0e"          # laranja LegisCheck
backgroundColor = "#000000"       # fundo geral (padrão do dark)
secondaryBackgroundColor = "#100F0F" # sidebar / cartões
textColor = "#FAFAFA"             # texto
